version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_deploy/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: buryatia_nginx

  app:
    build:
      context: .
      dockerfile: _deploy/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: buryatia_app

  db:
    image: mysql/mysql-server:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: buryatia_db

#    mysql:
#        image: 'mysql/mysql-server:8.0'
#        ports:
#            - '${FORWARD_DB_PORT:-3306}:3306'
#        environment:
#            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ROOT_HOST: '%'
#            MYSQL_DATABASE: '${DB_DATABASE}'
#            MYSQL_USER: '${DB_USERNAME}'
#            MYSQL_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ALLOW_EMPTY_PASSWORD: 1
#        volumes:
#            - 'sail-mysql:/var/lib/mysql'
#            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
#        networks:
#            - sail
#        healthcheck:
#            test:
#                - CMD
#                - mysqladmin
#                - ping
#                - '-p${DB_PASSWORD}'
#            retries: 3
#            timeout: 5s

#    meilisearch:
#        image: 'getmeili/meilisearch:latest'
#        ports:
#            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
#        environment:
#            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
#        volumes:
#            - 'sail-meilisearch:/meili_data'
#        networks:
#            - sail
#        healthcheck:
#            test:
#                - CMD
#                - wget
#                - '--no-verbose'
#                - '--spider'
#                - 'http://127.0.0.1:7700/health'
#            retries: 3
#            timeout: 5s

#networks:
#    sail:
#        driver: bridge
#volumes:
#    sail-mysql:
#        driver: local
#    sail-redis:
#        driver: local
#    sail-meilisearch:
#        driver: local
